### ISSUE TITLE
Platform showing wrong number of samples

### ISSUE THREAD

**Issue by jhalkilahti** [bfrgoncalves/INNUENDO_REST_API#110]
There's only 100 samples in the project but the "loading screen" shows 200 after hitting update .

![image](https://user-images.githubusercontent.com/29059353/36899248-ea41b7a2-1e26-11e8-85e1-dcd7477a2fb1.png)

**Comment by bfrgoncalves** [comment]
This issue is now solved as part of 16c90ccf09310a6ff6ed8af38cc38612949afd4c
Job status are now checked by strain and not by job submission id.
