### ISSUE TITLE
Abricate annotation window header

### ISSUE THREAD

**Issue by jhalkilahti** [bfrgoncalves/INNUENDO_REST_API#114]
The window for abricate annotation header should be changed from "Anti-microbial annotation gene list for sample: " to "Annotation gene list for sample:" or something similar since the annotations contain more than just anti-microbial stuff.

**Comment by ODiogoSilva** [comment]
Yes, that makes sense. However, would you consider something like "Anti-microbial, virulence and plasmid annotation"? This is only to avoid confusion when we add prokka to the reports, which would have a general title like the "Annotation gene list for sample" suggestion.

**Comment by jhalkilahti** [comment]
The "Anti-microbial, virulence and plasmid annotation" or anything with a bit more broader scope is fine by me. I was only pointing out that the current header is bit misleading.
