### ISSUE TITLE
Quality control summary not showing properly

### ISSUE THREAD

**Issue by jhalkilahti** [bfrgoncalves/INNUENDO_REST_API#117]
![image](https://user-images.githubusercontent.com/29059353/38084950-75ad0ec8-3357-11e8-8ed9-8f4f304102f9.png)
Almost all failed samples show this as the quality control summary. They have all failed the FastQC part of the pipeline. Didn't go through all the samples logs but 'Per sequence GC content', 'FAIL' is the only part some checked samples failed on.

**Comment by ODiogoSilva** [comment]
Fixed via https://github.com/ODiogoSilva/report-nf/commit/e594fddab0b07944c21d543ba02179c8ec41b8b5
