### ISSUE TITLE
Sample metadata showing differences

### ISSUE THREAD

**Issue by jhalkilahti** [bfrgoncalves/INNUENDO_REST_API#141]
When submitting samples as a batch the metadata columns left blank are marked as "NA" on the Strains page but are left empty if submission has been done manually sample by sample.

**Comment by bfrgoncalves** [comment]
Now all tables empty cells in the projects and modify metadata section of the platform are populated with "NA". Fixed on commit e37adc762d1058b22268bfc826ed3cd1e0c2dada
