### ISSUE TITLE
Changing password to platform

### ISSUE THREAD

**Issue by jhalkilahti** [bfrgoncalves/INNUENDO_REST_API#144]
Changing the user password for the platform appears to have an issue. When the password was changed I got an email from phylovizonline@gmail.com. The new password worked for the platform when logging in but not for the sftp where I had to use the old password. After a day the new password was totally reset to the old one as I couldn't log in to the platform using the new password at all but instead the old one worked without any issues.

**Comment by bfrgoncalves** [comment]
This issue is now solved.
